### ISSUE TITLE
How to workaround using Stack for building html

### ISSUE THREAD

**Issue by hafizhmakmur** [ucsd-progsys/liquidhaskell-tutorial#103]
When I execute "make html" the log outputs

```
stack run filters-toc src/ templates/pagemeta.template templates/index.template dist/page.template dist/index.lhs dist/links.txt
Cabal file info not found for Diff-0.3.4, updating
Selected mirrot https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
```
and it stucks here.

And when I try to cancel it, it says
```
make: *** [Makefile:84: dist/index.lhs] Interrupt
```

Any steps that I have missed?

**Comment by hafizhmakmur** [comment]
After searching for the solution I found that it looks like it's a stack problem
https://github.com/commercialhaskell/stack/issues/2240 
https://github.com/commercialhaskell/stack/issues/1223

It looks like I won't be able to use stack because every command will be too slow. Henceforth I'd like to ask whether there is any way to build the project without stack? I have a working ghc and cabal so is there a way to maybe modify the makefile to use them instead?

**Comment by ranjitjhala** [comment]
Dear Hafizh,

Yes all of this is only to build the webpage is there a reason you are
trying to do that locally? In principle it should be straightforward to use
the new cabal to do everything as LH builds just fine with it. But in
practice I will have to see when I can find the time. (It should be an easy
application of the stack2cabal script I saw online...)

Ranjit.

**Comment by hafizhmakmur** [comment]
Dear @ranjitjhala ,

Inspired by https://liquid.kosmikus.org/ I'm trying to make my own web page that will be similar to the tutorials. So far I'm trying to just change the commands in the makefile, specifically
```
# bin
## INDEXER=stack exec -- runghc filters/Toc.hs
## PANDOC=pandoc
INDEXER=stack run filters-toc
PANDOC=stack exec -- pandoc
```
to
```
# bin
INDEXER=runghc filters/Toc.hs
PANDOC=pandoc
```
Do you think it will work? So far the latest hurdle I found with this is my difficulty in installing the Pandoc Hackage (https://github.com/jgm/pandoc/issues/6612) which I think is an independent problem from this but I'm afraid after I solved that problem I'll still found a new problem that will block me. 

Thank you for your attention!

**Comment by ranjitjhala** [comment]
Hi yes that should work!

**Comment by hafizhmakmur** [comment]
Thank you very much! I'll tell you whether it works after I solve this pandoc issue.

**Comment by hafizhmakmur** [comment]
Dear @ranjitjhala,

I have a 4GB device so I'm having difficulty to install the latest pandoc. So I'm forced to install pandoc-2.7.3 and along with it downgrade my ghc to 8.6.5 . After that, I also need to fix some conversions from String to T.Text in the filters code but finally it works! Now I'm able to make the articles with your generator. Thank you very much for your assistance. :D

**Comment by ranjitjhala** [comment]
Wow excellent, if you have a PR to help simplify that would be great (or
even a branch for building on ghc 8.6.5)
