### ISSUE TITLE
Chapter 4: how do included .spec files work?

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell-tutorial#28]
In chapter 4, the use of external .spec files was mentioned: https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/src/04-poly.lhs#L93-L98

However, how this mechanism works is never explained. How does one include a .spec file? What rules are associated with these includes? 

I've submitted a PR for my review of this chapter, but I consider this to be an outstanding issue.

If somebody can post a brief explanation for how this works, I'll see it get included in the book.

**Comment by grncdr** [comment]
I'm also curious about this. It seems like the `liquid` checker ships a bunch of includes itself, but there's no mention of how to add your own.

**Comment by ranjitjhala** [comment]
Hi @christetreault and @grncdr  --

sorry this seems to have slipped through the cracks. 

The `.spec` files are somewhat in flux, but here's how to use them:

https://github.com/ucsd-progsys/liquidhaskell/blob/master/README.md#modules-without-code

Can you let me know if the above makes sense? And if so, I'll add it (or an improvement) to the 
tutorial?

Many thanks!

Ranjit.

**Comment by grncdr** [comment]
That explanation works for me. It might be a good idea to put more emphasis on the fact that LH has ships includes as part of it's prelude, since I tried copying the definitions in the tutorial only to find out they conflicted with builtin ones.

**Comment by christetreault** [comment]
Sounds good to me. Since they're in flux, I'll refrain from adding them to the book. Let me know if you'd like me to go ahead and do it anyway.

**Comment by ranjitjhala** [comment]
@Chris -- sure, can you add it for now? We can take it out later as needed.
Several folks have asked about this so I think we should put it in. Thanks!

**Comment by christetreault** [comment]
OK, I'll put it on my list.

**Comment by christetreault** [comment]
Should be closed by  #31.

**Comment by ranjitjhala** [comment]
Thanks @christetreault !

**Comment by grncdr** [comment]
I took a look at #28, that's a very nice improvement :)
