### ISSUE TITLE
Non-terminating sample code

### ISSUE THREAD

**Issue by pseudonom** [ucsd-progsys/liquidhaskell-tutorial#32]
Several pieces of code in the tutorial don't pass the termination checker. Should those bits of code be altered or should the tutorial explicitly mention `--no-termination` somewhere?

**Comment by ranjitjhala** [comment]
Hmm, thats a tricky one. Perhaps I should explicitly mention the `--no-termination` early on. What do you think might be a good spot? Thanks! Ranjit.

**Comment by pseudonom** [comment]
Maybe something like: https://github.com/ucsd-progsys/liquidhaskell-tutorial/pull/33?

**Comment by ranjitjhala** [comment]
Super, thanks! Merged it in!
