### ISSUE TITLE
Nothing to fix in exercise (Average, Maybe), chapter 6

### ISSUE THREAD

**Issue by goosetherumfoodle** [ucsd-progsys/liquidhaskell-tutorial#51]
The following exercise in chapter 6, seems to work fine, and liquidhaskell marks it as safe. So it's unclear what there is to fix.
```
average'      :: [Int] -> Maybe Int
average' xs
  | ok        = Just $ divide (sum xs) elems 
  | otherwise = Nothing 
  where
    elems     = size xs
    ok        = elems > 0 -- What expression goes here? 
```
Was `ok` supposed to be `undefined`?

**Comment by ranjitjhala** [comment]
Oops, looks like the "fix" was in. My bad!

**Comment by ranjitjhala** [comment]
Fixed, thanks @goosetherumfoodle !
