### ISSUE TITLE
Which description is correct?

### ISSUE THREAD

**Issue by waddlaw** [ucsd-progsys/liquidhaskell-tutorial#53]
Question: `expression` and `predicate` syntax.

[Readme in liquidhaskell repo](https://github.com/ucsd-progsys/liquidhaskell#formal-grammar-of-refinement-predicates)

## expression

```haskell
e := v                      -- variable
   | c                      -- constant
   | (e + e)                -- addition
   | (e - e)                -- subtraction
   | (c * e)                -- multiplication by constant
   | (v e1 e2 ... en)       -- uninterpreted function application
   | (if p then e else e)   -- if-then-else
```

## predicate

```haskell
p := (e r e)          -- binary relation
   | (v e1 e2 ... en) -- predicate (or alias) application
   | (p && p)         -- and
   | (p || p)         -- or
   | (p => p)         -- implies
   | (not p)          -- negation
   | true
   | false
```

But,  this tutorial is below:

## expression

```haskell
    e := v                   -- variable
       | c                   -- constant
       | e + e               -- addition
       | e - e               -- subtraction
       | c * e               -- linear multiply
       | v e1 e2 ... en      -- uninterpreted function application
```

## predicate

```haskell
    p := true
       | false
       | e r e           -- atomic binary relation
       | v e1 e2 ... en  -- predicate application
       | p  && p         -- and
       | p  || p         -- or
       | p ==> p         -- implies
       | p <=> p         -- if and only if
       | not p           -- negation
```

Both of a bit different. Which is correct?

**Comment by ranjitjhala** [comment]
I think the only difference between the two
is that the parentheses are explicit in the
LH README?

Normally, you shouldn't need the parentheses but
if there is any ambiguity, use it to avoid confusion.

e.g. with

   a && b || c

I _think_ the precedences work the way you expect,
i.e. && binds more tightly than || but I always write

   (a && b) || c

just to be sure :)

**Comment by waddlaw** [comment]
@ranjitjhala Thanks for your reply.

> I think the only difference between the two
is that the parentheses are explicit in the
LH README?

Yes of course.
And more, I think that `(if p then e else e)` of `expression` is different from LH README.
Also `==>`, `p <=> p` of `predicate`.

Thank you.

**Comment by waddlaw** [comment]
I think that is correct predicate syntax below:

```
p := (e r e)          -- binary relation
   | (v e1 e2 ... en) -- predicate (or alias) application
   | (p && p)         -- and
   | (p || p)         -- or
   | (p => p) | (p ==> p)         -- implies
   | (p <=> p)
   | (not p)          -- negation
   | true | True
   | false | False
```

To verified, I used `liquid v0.8.0.5`.
Let me clarify my understanding here.Is my understanding correct?

**Comment by ranjitjhala** [comment]
That is correct, thanks!

**Comment by waddlaw** [comment]
Can I update the document?
https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/src/02-logic.lhs#L106

**Comment by ranjitjhala** [comment]
Yes please, that would be most welcome! Thanks!

**Comment by waddlaw** [comment]
Merged. closing this issue.
