### ISSUE TITLE
liquidhaskell error about merge example

### ISSUE THREAD

**Issue by mhwombat** [ucsd-progsys/liquidhaskell-tutorial#76]
Liquidhaskell reports an error with one of the examples:

```
 /home/amy/liquidhaskell-tutorial/src/05-datatypes.lhs:338:1-5: Error: Liquid Type Mismatch
  
 338 | merge xs  Emp = xs
       ^^^^^
  
   Inferred type
     VV : {v : GHC.Prim.Addr# | v == "/home/amy/liquidhaskell-tutorial/src/05-datatypes.lhs:(338,1)-(342,39)|function merge"}
  
   not a subtype of Required type
     VV : {VV : GHC.Prim.Addr# | 5 < 4}
```

The code it's complaining about is this:

```
merge         :: (Ord a) => IncList a -> IncList a -> IncList a
merge xs  Emp = xs    <--- line 338
merge Emp ys  = ys
merge (x :< xs) (y :< ys)
  | x <= y    = x :< merge xs (y :< ys)
  | otherwise = y :< merge (x :< xs) ys
```

**Comment by mhwombat** [comment]
You can also see the error on the web page (http://ucsd-progsys.github.io/liquidhaskell-tutorial/05-datatypes.html) if you click the compile button.

**Comment by SkyZH** [comment]
I encountered the same error, but I found that add a line `merge _ _ = Emp` makes sense. Here's my code:
```haskell
merge :: (Ord a) => IncList a -> IncList a -> IncList a
merge Emp ys = ys
merge xs Emp = xs
merge (x :< xs) (y :< ys)
    | x <= y    = x :< (merge xs (y :< ys))
    | otherwise = y :< (merge (x :< xs) ys)
merge _ _ = Emp
```
This may pass liquid haskell safe check.

**Comment by ranjitjhala** [comment]
Yes this seems like some unfortunate consequence of how new versions of GHC
desugar pattern matches. This seems related to the issue #1396
Posted by @wkunkel.

Does the suggested extra case work? If so will update tutorial
appropriately.

**Comment by SkyZH** [comment]
Here's my code, and it passes Travis check.

https://github.com/SkyZH/playground.lhs/blob/master/src/Ex42.hs#L129
https://travis-ci.com/SkyZH/playground.lhs

**Comment by SkyZH** [comment]
I've already sent #78 yesterday :) @ranjitjhala
