### ISSUE TITLE
Arithmetic example 4 doesn't work in "Logic & SMT"

### ISSUE THREAD

**Issue by kubum** [ucsd-progsys/liquidhaskell-tutorial#77]
Code from the tutorial:

```haskell
{-@ ax3 :: Int -> Int -> TRUE @-}
ax3 :: Int -> Int -> Bool
ax3 x y = (0 <= x) ==> (0 <= y) ==> (0 <= x + y)
```

LiquidHaskell response:

```
   67 | ax3 x y = (0 <= x) ==> (0 <= y) ==> (0 <= x + y)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Inferred type
     VV : {v : GHC.Types.Bool | v <=> ((0 <= x => 0 <= y) => 0 <= x + y)}

   not a subtype of Required type
     VV : {VV : GHC.Types.Bool | VV}

   In Context
     x : GHC.Types.Int

     y : GHC.Types.Int
```

- *GHC:* 8.6.3
- *Liquid:* LiquidHaskell Version 0.8.4.0, Git revision 57213512a9d69093c12d644b21dbf9da95811894 (dirty)

What was the original intention? For example the code below passes:

```haskell
ax3 x y = (x >= 0 && y >= 0) ==> (x + y >= 0)
```

**Comment by kubum** [comment]
Ah, forgotten 

```
infixr 9 ==>
```

**Comment by ranjitjhala** [comment]
Thanks! Maybe the “infix” annotation should be more prominent in the text?

**Comment by kubum** [comment]
Hi @ranjitjhala! 

Sorry for opening this noisy issue. It just has happened, because I have started working against the web page http://ucsd-progsys.github.io/liquidhaskell-tutorial/01-intro.html playing with the example without even realising that there is a corresponding .lhs that hides all the prerequisites. Maybe there is a note somewhere that refers to it, but I weren't able to locate it. It would be fantastic if there would be a collapsed brief of the type signatures, extensions in the beginning of each chapter. What do you think worth a PR?
