### ISSUE TITLE
Cannot find Data.Vector

### ISSUE THREAD

**Issue by mmport80** [ucsd-progsys/liquidhaskell-tutorial#82]
I get an error when trying the following. Any hints? The chapters until now are OK.

I cloning latest tutorial and liquid haskell from Github, running on Debian.

> stack exec -- liquid src/04-poly.lhs
> Downloaded lts-12.2 build plan.    
> Preparing to install GHC to an isolated location.
> This will not interfere with any system-level installation.
> Downloaded ghc-8.4.3.                                      
> Installed GHC.                                                                
> LiquidHaskell Version 0.8.6.0, Git revision f4fe82cd03fbe906379c8ebeac5ec3efae0b4cd8 (dirty) [develop@f4fe82cd03fbe906379c8ebeac5ec3efae0b4cd8 (Mon Jun 24 10:55:17 2019 +0200)]
> Copyright 2013-19 Regents of the University of California. All Rights Reserved.
> 
> Targets: src/04-poly.lhs
> 
> **** [Checking: src/04-poly.lhs] ***********************************************
> liquid: VectorBounds: Could not find module ‘Data.Vector’
> Perhaps you meant Data.Functor (from base-4.11.1.0)
> Use -v to see a list of the files searched for.

**Comment by ranjitjhala** [comment]
Strange! Can you do a “stack install vector” in the directory and then try?

**Comment by mmport80** [comment]
yep I spotted that too! all good now.

**Comment by mmport80** [comment]
My mistake, Emacs still shows after successful `stack install`

```
Targets: flycheck_04-poly.lhs
^[[1;94m 
**** [Checking: flycheck_04-poly.lhs] ******************************************
^[[0mliquid: VectorBounds: Could not find module ‘Data.Vector’
Perhaps you meant Data.Functor (from base-4.12.0.0)                                                                                                   Use -v to see a list of the files searched for.

Try installing a more recent version of haskell-liquid, and please open a bug report if the issue persists in the latest release.  Thanks!
```

and compiling directly returns

> stack exec -- liquid src/04-poly.lhs 
> LiquidHaskell Version 0.8.6.0, Git revision f4fe82cd03fbe906379c8ebeac5ec3efae0b4cd8 (dirty) [develop@f4fe82cd03fbe906379c8ebeac5ec3efae0b4cd8 (Mon Jun 24 10:55:17 2019 +0200)] 
> Copyright 2013-19 Regents of the University of California. All Rights Reserved.
> 
> Targets: src/04-poly.lhs
> 
> **** [Checking: src/04-poly.lhs] ***********************************************
> liquid: /home/john/.stack/programs/x86_64-linux/ghc-8.4.3/lib/ghc-8.4.3/ghc-prim-0.5.2.0/HSghc-prim-0.5.2.0.o: unknown symbol `stg_MUT_ARR_PTRS_FROZEN0_info'
> liquid: liquid: unable to load package `ghc-prim-0.5.2.0'

**Comment by ranjitjhala** [comment]
Hmm.

There's something odd going on, LH version 0.8.6.0 should be running with
ghc-8.6.4, why is it running ghc-8.4.3 ?

**Comment by mmport80** [comment]
aha! OK I will blow the install away and try again - thanks, really
enjoying LH so far!

**Comment by ranjitjhala** [comment]
Great! Did that work?

**Comment by mmport80** [comment]
Will test later today

**Comment by mmport80** [comment]
I think 8.4.3 come from here: https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/stack.yaml#L1

Still working on the Vector issue.. Will let you know what I find..

**Comment by ranjitjhala** [comment]
Aha -- this is a mismatch between the LH stack-version and the tutorial
version! My bad, let me fix.

**Comment by mmport80** [comment]
yep, same LTS did the trick! thanks again for all the hard work.
