### ISSUE TITLE
Trouble with Chapter 11

### ISSUE THREAD

**Issue by hafizhmakmur** [ucsd-progsys/liquidhaskell-tutorial#98]
First I'd like to inform that the signature for `mallocForeignPtrBytes :: Int -> ForeignPtr a` is wrong. It should be `mallocForeignPtrBytes :: Int -> IO (ForeignPtr a)` which strangely is right in the source code but not in the tutorial text.

Second, as seen [in this code](http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1591152047_9614.hs), I'm already very sure that I have made a right `create` function so that `bsGHC` is deemed as correct but somehow the `pack` function after that is still deemed wrong.  

I have also looked at the source code of the `create'` function and it's the same and `create` is also deemed right when I type it into the website so it seems that there's some auxiliary code that I have to type but I haven't. It also affects any next practices so I think I need to know what's wrong with this before I move on.

**Comment by ranjitjhala** [comment]
(Thanks for pointing out the typo in the informal text for
mallocForeignPtrBytes
-- will fix!)

The spec for `unsafeTake` has some precondition about `bOff` which is not
established by `pack`.

A hint: the type for `unsafeTake` is much simpler -- you can write it
_without_ referring to `bOff` and only using the `bLen`.

Try to work it out (you're _very_ close) -- but if not, click below

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1591367347_9690.hs

**Comment by hafizhmakmur** [comment]
Thank you very much! I see that the function ignores the `bLen` entirely so I never thought that `bLen` would be used in the specification. :D Once again thank you very much!

NB: In Figure 12.5 the most left triangle should be "ll" not "lr". Also I can't run Chapter 10 page entirely because of some missing imports that I can't repair because the code also don't recognize `import`. @ranjitjhala
